// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotasWebAPI.Contexto;

namespace NotasWebAPI.Migrations
{
    [DbContext(typeof(CelinaDbContext))]
    partial class CelinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotasWebAPI.Entitys.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<DateTime>("DataDeAlteracao");

                    b.Property<DateTime>("DataDeCadastro");

                    b.Property<string>("EntityGuid");

                    b.Property<string>("Estado");

                    b.Property<bool>("Lixeira");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Numero");

                    b.Property<Guid>("UserId");

                    b.Property<Guid?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("NotasWebAPI.Entitys.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<DateTime>("DataDeAlteracao");

                    b.Property<DateTime>("DataDeCadastro");

                    b.Property<DateTime?>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("EntityGuid");

                    b.Property<int>("Idade");

                    b.Property<bool>("Lixeira");

                    b.Property<string>("Nome");

                    b.Property<string>("TipoNota");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("NotasWebAPI.Entitys.Endereco", b =>
                {
                    b.HasOne("NotasWebAPI.Entitys.Usuario")
                        .WithMany("Endereco")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
